# copy & paste this file as mock-accelerator.toml at project root to use

slot_name = "cuda"
device_plugin_name = "CUDADevice"
human_readable_name = "fGPU"
description = "CUDA-capable GPU (fractional)"
display_unit = "fGPU"
number_format = "#,###.00"
display_icon = "gpu1"

devices = [
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d01", model_name = "CUDA GPU", numa_node = 0, subproc_count = 108, memory_size = "40G", is_mig_device = false },
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d02", model_name = "CUDA GPU", numa_node = 1, subproc_count = 108, memory_size = "40G", is_mig_device = false },
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d03", model_name = "MIG-20g", numa_node = 0, subproc_count = 56, memory_size = "20G", is_mig_device = true },
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d03", model_name = "MIG-10g", numa_node = 0, subproc_count = 28, memory_size = "10G", is_mig_device = true },
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d03", model_name = "MIG-10g", numa_node = 0, subproc_count = 28, memory_size = "10G", is_mig_device = true },
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d04", model_name = "MIG-5g", numa_node = 1, subproc_count = 14, memory_size = "5G", is_mig_device = true },
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d04", model_name = "MIG-5g", numa_node = 1, subproc_count = 14, memory_size = "5G", is_mig_device = true },
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d04", model_name = "MIG-5g", numa_node = 1, subproc_count = 14, memory_size = "5G", is_mig_device = true },
  { mother_uuid = "c59395cd-ac91-4cd3-a1b0-3d2568aa2d04", model_name = "MIG-5g", numa_node = 1, subproc_count = 14, memory_size = "5G", is_mig_device = true },
]

[attributes]
nvidia_driver = "450.0.0"
cuda_runtime = "11.0"
