name: 'Test Actions'

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.0
